<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dioearticlesystem"
 *
 * Auto generated by Extension Builder 2021-03-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Diö Artikelsystem',
    'description' => '',
    'category' => 'plugin',
    'author' => 'HCB',
    'author_email' => '',
    'state' => 'alpha',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'vhs' => '6.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
