base: 'https://iam.dioe.at/'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: en-US
    direction: ''
    flag: de
    languageId: 0
rootPageId: 60
routeEnhancers:
  Dioearticlesystem:
    type: Plugin
    limitToPages: 140
    routePath: '/{dioeArticle}/{action}{controller}'
    namespace: tx_dioearticlesystem_view
    defaults:
      action: show
      controller: DioeArticle
    requirements:
      dioeArticle: '[0-9]{1,9}'
websiteTitle: ''
