<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hcb_iamdioe_meme"
 *
 * Auto generated by Extension Builder 2020-03-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'iamDioe Meme',
    'description' => 'iamDioe Meme Generator und Auflistung mit Voting',
    'category' => 'plugin',
    'author' => 'hcb',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
